language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - make
  - pip install python-coveralls
# command to run tests
script:
  - make test
after_sccess:
  - coveralls